spring:
  application:
    name: fitme
  profiles:
    active: local # 기본 실행 프로파일

  # 사용할 DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
